/// Maps coarse catalog target-muscle tokens (lowercase) to FULL atlas ids
/// (left + right). Used for fallback highlighting when an exercise has no
/// curated head-level mapping.
///
/// Every id here is verified against `flutter_body_atlas` MuscleCatalog by
/// `coarse_muscle_map_test.dart`.
const Map<String, List<String>> kCoarseMuscleToAtlasIds = {
  'pectorals': ['pectoralis_major_l', 'pectoralis_major_r'],
  'chest': ['pectoralis_major_l', 'pectoralis_major_r'],
  'biceps': [
    'biceps_brachii_caput_longum_l',
    'biceps_brachii_caput_longum_r',
    'biceps_brachii_caput_breve_l',
    'biceps_brachii_caput_breve_r',
  ],
  'triceps': [
    'triceps_brachii_caput_longum_l',
    'triceps_brachii_caput_longum_r',
    'triceps_brachii_caput_laterale_l',
    'triceps_brachii_caput_laterale_r',
    'triceps_brachii_caput_mediale_l',
    'triceps_brachii_caput_mediale_r',
  ],
  'delts': [
    'anterior_deltoid_l',
    'anterior_deltoid_r',
    'lateral_deltoid_l',
    'lateral_deltoid_r',
    'posterior_deltoid_l',
    'posterior_deltoid_r',
  ],
  'deltoids': [
    'anterior_deltoid_l',
    'anterior_deltoid_r',
    'lateral_deltoid_l',
    'lateral_deltoid_r',
    'posterior_deltoid_l',
    'posterior_deltoid_r',
  ],
  'shoulders': [
    'anterior_deltoid_l',
    'anterior_deltoid_r',
    'lateral_deltoid_l',
    'lateral_deltoid_r',
    'posterior_deltoid_l',
    'posterior_deltoid_r',
  ],
  'lats': ['latissimus_dorsi_l', 'latissimus_dorsi_r'],
  'upper back': [
    'trapezius_upper_l',
    'trapezius_upper_r',
    'trapezius_middle_l',
    'trapezius_middle_r',
    'infraspinatus_l',
    'infraspinatus_r',
  ],
  'traps': [
    'trapezius_upper_l',
    'trapezius_upper_r',
    'trapezius_middle_l',
    'trapezius_middle_r',
    'trapezius_lower_l',
    'trapezius_lower_r',
  ],
  'abs': [
    'rectus_abdominis_1',
    'rectus_abdominis_2_l',
    'rectus_abdominis_2_r',
    'rectus_abdominis_3_l',
    'rectus_abdominis_3_r',
    'rectus_abdominis_4_l',
    'rectus_abdominis_4_r',
  ],
  'abductors': [
    'gluteus_medius_1_l',
    'gluteus_medius_1_r',
    'gluteus_medius_2_l',
    'gluteus_medius_2_r',
  ],
  'adductors': [
    'adductor_longus_l',
    'adductor_longus_r',
    'adductor_magnus_l',
    'adductor_magnus_r',
    'gracilis_l',
    'gracilis_r',
    'pectineus_l',
    'pectineus_r',
  ],
  'quads': [
    'rectus_femoris_l',
    'rectus_femoris_r',
    'vastus_lateralis_l',
    'vastus_lateralis_r',
    'vastus_medialis_l',
    'vastus_medialis_r',
  ],
  'hamstrings': [
    'biceps_femoris_l',
    'biceps_femoris_r',
    'semitendinosus_l',
    'semitendinosus_r',
    'semimembranosus_1_l',
    'semimembranosus_1_r',
  ],
  'glutes': [
    'gluteus_maximus_l',
    'gluteus_maximus_r',
    'gluteus_medius_1_l',
    'gluteus_medius_1_r',
  ],
  'calves': ['gastrocnemius_l', 'gastrocnemius_r'],
  'forearms': [
    'brachioradialis_l',
    'brachioradialis_r',
    'flexor_carpi_radialis_l',
    'flexor_carpi_radialis_r',
    'extensor_carpi_radialis_longus_l',
    'extensor_carpi_radialis_longus_r',
  ],
};
