import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:fitnation/models/Workout.dart';
import 'package:fitnation/services/gemini_service.dart';
import 'package:uuid/uuid.dart'; // For generating unique IDs
import 'package:fitnation/api/API_Services.dart'; // Import ApiService
import 'package:fitnation/providers/auth_provider.dart'; // Import authProvider
import 'package:fitnation/providers/data_providers.dart'; // Import apiServiceProvider
import 'package:flutter/foundation.dart'; // Import for debugPrint
import 'package:fitnation/services/connectivity_service.dart'; // Import ConnectivityService
import 'package:fitnation/providers/workout_generation_provider.dart'; // Import workout generation provider

// StateNotifier for managing generated workout plans
class GeminiWorkoutNotifier extends StateNotifier<List<Workout>> {
  final GeminiService _geminiService;
  final ApiService _apiService; // Add ApiService
  final Uuid _uuid;
  final Ref _ref; // Add Ref to access other providers

  GeminiWorkoutNotifier(this._geminiService, this._apiService, this._ref)
    : _uuid = const Uuid(),
      super([]);

  Future<void> _loadWorkoutPlans() async {
    debugPrint('GeminiWorkoutNotifier: Loading workout plans.');
    try {
      final authState = _ref.read(authProvider);
      String? currentUserId;
      if (authState is Authenticated) {
        currentUserId = authState.user.id;
        debugPrint(
          'GeminiWorkoutNotifier: User authenticated with ID: $currentUserId',
        );
        final loadedPlans = await _apiService.getWorkoutPlans(
          skip: 0, // Adjust as needed for pagination
          limit: 100, // Adjust as needed
        );
        state = loadedPlans;
        debugPrint(
          'GeminiWorkoutNotifier: Successfully loaded ${loadedPlans.length} workout plans.',
        );
      } else {
        debugPrint(
          'GeminiWorkoutNotifier: User not authenticated. Cannot load workout plans.',
        );
        state = []; // Clear plans if not authenticated
      }
    } on NoInternetException catch (e) {
      debugPrint(
        'GeminiWorkoutNotifier: No internet connection while loading workout plans: ${e.message}',
      );
      state = []; // Clear plans on no internet
      rethrow; // Re-throw to be caught by UI if needed
    } catch (e) {
      debugPrint('GeminiWorkoutNotifier: Error loading workout plans: $e');
      state = []; // Clear plans on error
      rethrow; // Re-throw to be caught by UI if needed
    }
  }

  Future<void> generateWorkoutPlan(Map<String, dynamic> userInfo) async {
    debugPrint(
      'GeminiWorkoutNotifier: generateWorkoutPlan called with userInfo: $userInfo',
    );

    // Start the generation process
    _ref.read(workoutGenerationProvider.notifier).startGeneration();

    try {
      final authState = _ref.read(authProvider);
      String? currentUserId;
      if (authState is Authenticated) {
        currentUserId = authState.user.id;
        debugPrint(
          'GeminiWorkoutNotifier: User authenticated with ID: $currentUserId',
        );
      } else {
        debugPrint(
          'GeminiWorkoutNotifier: User not authenticated. Throwing exception.',
        );
        _ref
            .read(workoutGenerationProvider.notifier)
            .setError('User not authenticated. Cannot generate workout plan.');
        throw Exception(
          'User not authenticated. Cannot generate workout plan.',
        );
      }

      // Add a unique ID to the user info for the workout plan
      userInfo['workout_plan_id'] = _uuid.v4();

      // Convert equipment list to comma-separated string if it's a list
      if (userInfo['equipment'] != null &&
          userInfo['equipment'] is List<String>) {
        userInfo['equipment'] = (userInfo['equipment'] as List<String>).join(
          ', ',
        );
      }

      debugPrint(
        'GeminiWorkoutNotifier: Calling GeminiService to generate workout plan...',
      );

      // Update status to parsing
      _ref.read(workoutGenerationProvider.notifier).updateParsingStep();

      final Workout newWorkout = await _geminiService.generateWorkoutPlan(
        userInfo,
      );
      debugPrint(
        'GeminiWorkoutNotifier: Workout plan generated by GeminiService: ${newWorkout.name}',
      );

      // Update status to processing
      _ref.read(workoutGenerationProvider.notifier).updateProcessingStep();

      state = [
        ...state,
        newWorkout,
      ]; // TODO: might wanna add savedWorkout here instead of newWorkout
      debugPrint('GeminiWorkoutNotifier: State updated with new workout plan.');

      // Update status to handling
      _ref.read(workoutGenerationProvider.notifier).updateHandlingStep();

      // Save to backend
      debugPrint('GeminiWorkoutNotifier: Saving workout plan to backend...');
      final savedWorkout = await _apiService.saveWorkoutPlan(
        newWorkout,
        userInfo,
      );
      debugPrint(
        'GeminiWorkoutNotifier: Workout plan saved to backend: $savedWorkout',
      );

      // Complete the generation process
      _ref.read(workoutGenerationProvider.notifier).completeGeneration();
    } on NoInternetException catch (e) {
      debugPrint(
        'GeminiWorkoutNotifier: No internet connection while generating workout plan: ${e.message}',
      );
      _ref
          .read(workoutGenerationProvider.notifier)
          .setError(
            'No internet connection. Please check your connection and try again.',
          );
      rethrow; // Re-throw to be caught by UI if needed
    } catch (e) {
      // Handle error, e.g., log it or show a user-friendly message
      debugPrint('Error generating workout plan in Notifier: $e');
      _ref
          .read(workoutGenerationProvider.notifier)
          .setError('Failed to generate workout plan: ${e.toString()}');
      rethrow; // Re-throw to be caught by UI if needed
    }
  }

  // You might want methods to clear plans, load saved plans, etc.
  void clearPlans() {
    state = [];
  }
}

final geminiWorkoutPlanProvider =
    StateNotifierProvider<GeminiWorkoutNotifier, List<Workout>>((ref) {
      final notifier = GeminiWorkoutNotifier(
        GeminiService(),
        ref.watch(apiServiceProvider), // Pass ApiService
        ref, // Pass Ref
      );

      // Listen to authProvider to load workout plans once authenticated
      ref.listen<AuthState>(authProvider, (_, authState) {
        if (authState is Authenticated) {
          notifier._loadWorkoutPlans();
        } else {
          notifier.clearPlans(); // Clear plans if user logs out
        }
      });

      return notifier;
    });
