import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:fitnation/models/MealPlan.dart';
import 'package:fitnation/services/gemini_service.dart';
import 'package:uuid/uuid.dart'; // For generating unique IDs
import 'package:fitnation/api/API_Services.dart'; // Import ApiService
import 'package:fitnation/providers/auth_provider.dart'; // Import authProvider
import 'package:fitnation/providers/data_providers.dart'; // Import apiServiceProvider
import 'package:flutter/foundation.dart'; // Import for debugPrint
import 'package:fitnation/services/connectivity_service.dart'; // Import ConnectivityService

// StateNotifier for managing generated meal plans
class GeminiMealPlanNotifier extends StateNotifier<List<MealPlan>> {
  final GeminiService _geminiService;
  final ApiService _apiService; // Add ApiService
  final Uuid _uuid;
  final Ref _ref; // Add Ref to access other providers

  GeminiMealPlanNotifier(this._geminiService, this._apiService, this._ref)
      : _uuid = const Uuid(),
        super([]);

  Future<void> _loadMealPlans() async {
    debugPrint('GeminiMealPlanNotifier: Loading meal plans.');
    try {
      final authState = _ref.read(authProvider);
      String? currentUserId;
      if (authState is Authenticated) {
        currentUserId = authState.user.id;
        debugPrint('GeminiMealPlanNotifier: User authenticated with ID: $currentUserId');
        final loadedPlans = await _apiService.getMealPlans(
          skip: 0, // Adjust as needed for pagination
          limit: 100, // Adjust as needed
        );
        state = loadedPlans;
        debugPrint('GeminiMealPlanNotifier: Successfully loaded ${loadedPlans.length} meal plans.');
      } else {
        debugPrint('GeminiMealPlanNotifier: User not authenticated. Cannot load meal plans.');
        state = []; // Clear plans if not authenticated
      }
    } on NoInternetException catch (e) {
      debugPrint('GeminiMealPlanNotifier: No internet connection while loading meal plans: ${e.message}');
      state = []; // Clear plans on no internet
      rethrow; // Re-throw to be caught by UI if needed
    } catch (e) {
      debugPrint('GeminiMealPlanNotifier: Error loading meal plans: $e');
      state = []; // Clear plans on error
      rethrow; // Re-throw to be caught by UI if needed
    }
  }

  Future<void> generateMealPlan(Map<String, dynamic> userInfo) async {
    debugPrint('GeminiMealPlanNotifier: generateMealPlan called with userInfo: $userInfo');
    try {
      final authState = _ref.read(authProvider);
      String? currentUserId;
      if (authState is Authenticated) {
        currentUserId = authState.user.id;
        debugPrint('GeminiMealPlanNotifier: User authenticated with ID: $currentUserId');
      } else {
        debugPrint('GeminiMealPlanNotifier: User not authenticated. Throwing exception.');
        throw Exception('User not authenticated. Cannot generate meal plan.');
      }

      // Add a unique ID to the user info for the meal plan
      userInfo['meal_plan_id'] = _uuid.v4();
      debugPrint('GeminiMealPlanNotifier: Calling GeminiService to generate meal plan...');
      final MealPlan newMealPlan = await _geminiService.generateMealPlan(userInfo);
      debugPrint('GeminiMealPlanNotifier: Meal plan generated by GeminiService: ${newMealPlan.name}');

      // Save to backend
      debugPrint('GeminiMealPlanNotifier: Saving meal plan to backend...');
      final savedMealPlan = await _apiService.saveMealPlan(newMealPlan);
      debugPrint('GeminiMealPlanNotifier: Meal plan saved to backend.');
      state = [...state, savedMealPlan]; // Add the new meal plan to the list
      debugPrint('GeminiMealPlanNotifier: State updated with new meal plan.');
    } on NoInternetException catch (e) {
      debugPrint('GeminiMealPlanNotifier: No internet connection while generating meal plan: ${e.message}');
      rethrow; // Re-throw to be caught by UI if needed
    } catch (e) {
      // Handle error, e.g., log it or show a user-friendly message
      debugPrint('Error generating meal plan in Notifier: $e');
      rethrow; // Re-throw to be caught by UI if needed
    }
  }

  // You might want methods to clear plans, load saved plans, etc.
  void clearPlans() {
    state = [];
  }
}

final geminiMealPlanProvider = StateNotifierProvider<GeminiMealPlanNotifier, List<MealPlan>>((ref) {
  final notifier = GeminiMealPlanNotifier(
    GeminiService(),
    ref.watch(apiServiceProvider), // Pass ApiService
    ref, // Pass Ref
  );

  // Listen to authProvider to load meal plans once authenticated
  ref.listen<AuthState>(authProvider, (_, authState) {
    if (authState is Authenticated) {
      notifier._loadMealPlans();
    } else {
      notifier.clearPlans(); // Clear plans if user logs out
    }
  });

  return notifier;
});
