// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSrZ5_HdDgHO7E2rAk52ZUwlk12O0IFek',
    appId: '1:867243651880:web:2ad920efca2624c761161d',
    messagingSenderId: '867243651880',
    projectId: 'pulse',
    authDomain: 'athltiq.firebaseapp.com',
    storageBucket: 'athltiq.firebasestorage.app',
    measurementId: 'G-JD26SJKBY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCppOKelOuINsL0NgMdHCt5MmvQQgVVxmk',
    appId: '1:867243651880:android:85f3e5dcdf27fbd261161d',
    messagingSenderId: '867243651880',
    projectId: 'pulse',
    storageBucket: 'athltiq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh8OgYchi5MomWBX3VRnv-v_QvzC4CDkM',
    appId: '1:867243651880:ios:08bb40d8a839acab61161d',
    messagingSenderId: '867243651880',
    projectId: 'pulse',
    storageBucket: 'athltiq.firebasestorage.app',
    iosBundleId: 'com.codenamex.pulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh8OgYchi5MomWBX3VRnv-v_QvzC4CDkM',
    appId: '1:867243651880:ios:08bb40d8a839acab61161d',
    messagingSenderId: '867243651880',
    projectId: 'pulse',
    storageBucket: 'athltiq.firebasestorage.app',
    iosBundleId: 'com.codenamex.pulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSrZ5_HdDgHO7E2rAk52ZUwlk12O0IFek',
    appId: '1:867243651880:web:d5bb3745a18886c061161d',
    messagingSenderId: '867243651880',
    projectId: 'athltiq',
    authDomain: 'athltiq.firebaseapp.com',
    storageBucket: 'athltiq.firebasestorage.app',
    measurementId: 'G-33K9QXCL1C',
  );
}
