-- Ensure you are connected to the 'athlytiq' database
-- \c athlytiq;

-- Disable triggers to avoid issues with created_at/updated_at if they are auto-managed by triggers
-- and you want to set specific past timestamps.
-- For this dummy data, we'll use NOW() or intervals from NOW(), so disabling triggers might not be strictly necessary
-- but can be useful if you were inserting historical data.
-- SET session_replication_role = 'replica';

-- Dummy Users (assuming UUIDs are generated by default or you can generate them)
-- Replace with actual UUIDs if your application/DB doesn't auto-generate them on INSERT
-- For Supabase, gen_random_uuid() is available.
DO $$
DECLARE
    user_alice_id UUID := gen_random_uuid();
    user_bob_id UUID := gen_random_uuid();
    user_charlie_id UUID := gen_random_uuid();
BEGIN

    INSERT INTO users (id, username, email, password_hash, role, created_at, updated_at) VALUES
    (user_alice_id, 'alice_fit', 'alice@example.com', '$2b$12$D8OqWound.L0.s.xQ3xQ7O3j9G5B/C6E8wL.Lo.s.xQ3xQ7O3j9G', 'user', NOW() - INTERVAL '10 day', NOW() - INTERVAL '10 day'),
    (user_bob_id, 'bob_gym', 'bob@example.com', '$2b$12$D8OqWound.L0.s.xQ3xQ7O3j9G5B/C6E8wL.Lo.s.xQ3xQ7O3j9G', 'user', NOW() - INTERVAL '9 day', NOW() - INTERVAL '9 day'),
    (user_charlie_id, 'charlie_strong', 'charlie@example.com', '$2b$12$D8OqWound.L0.s.xQ3xQ7O3j9G5B/C6E8wL.Lo.s.xQ3xQ7O3j9G', 'trainer', NOW() - INTERVAL '8 day', NOW() - INTERVAL '8 day');

    -- Dummy Profiles
    INSERT INTO profiles (user_id, display_name, bio, profile_picture_url, fitness_goals, created_at, updated_at) VALUES
    (user_alice_id, 'Alice Fitness', 'Lover of HIIT and yoga. Join me on my fitness journey!', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=100&q=80', 'Improve flexibility and run a 5k.', NOW() - INTERVAL '10 day', NOW() - INTERVAL '10 day'),
    (user_bob_id, 'Bob Gymrat', 'Bodybuilding enthusiast. Always chasing the pump.', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=100&q=80', 'Increase bench press by 20kg.', NOW() - INTERVAL '9 day', NOW() - INTERVAL '9 day'),
    (user_charlie_id, 'Charlie Strong', 'Certified Personal Trainer. Helping you reach your peak performance. DM for plans!', 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=100&q=80', 'Help clients achieve their fitness dreams.', NOW() - INTERVAL '8 day', NOW() - INTERVAL '8 day');

    -- Dummy Public Posts
    -- Post 1 by Alice (Text and Image)
    INSERT INTO posts (user_id, content, media_url, post_type, privacy, created_at, updated_at) VALUES
    (user_alice_id, 'Just finished an amazing yoga session! Feeling so refreshed and centered. What are your favorite ways to unwind? #yoga #mindfulness #fitness', 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80', ARRAY['text']::post_type_enum[], 'public', NOW() - INTERVAL '5 day', NOW() - INTERVAL '5 day');

    -- Post 2 by Bob (Text only)
    INSERT INTO posts (user_id, content, media_url, post_type, privacy, created_at, updated_at) VALUES
    (user_bob_id, 'Hit a new personal record on squats today! 150kg! The grind pays off. #legday #powerlifting #gymmotivation', NULL, ARRAY['text']::post_type_enum[], 'public', NOW() - INTERVAL '4 day', NOW() - INTERVAL '4 day');

    -- Post 3 by Charlie (Text and Image - promoting services)
    INSERT INTO posts (user_id, content, media_url, post_type, privacy, created_at, updated_at) VALUES
    (user_charlie_id, 'Ready to take your fitness to the next level? I''m offering personalized training plans and one-on-one sessions. Check out my profile for more info or send me a DM! #personaltrainer #fitnesscoach #workoutplans', 'https://images.unsplash.com/photo-1594737625787-7a7a03b02a45?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80', ARRAY['text']::post_type_enum[], 'public', NOW() - INTERVAL '3 day', NOW() - INTERVAL '3 day');

    -- Post 4 by Alice (Text only - question to engage)
    INSERT INTO posts (user_id, content, media_url, post_type, privacy, created_at, updated_at) VALUES
    (user_alice_id, 'What''s everyone''s favorite healthy snack for a quick energy boost during the day? Looking for new ideas! #healthysnacks #nutrition #fitfood', NULL, ARRAY['text']::post_type_enum[], 'public', NOW() - INTERVAL '2 day', NOW() - INTERVAL '2 day');
    
    -- Post 5 by Bob (Text and Image - workout shot)
    INSERT INTO posts (user_id, content, media_url, post_type, privacy, created_at, updated_at) VALUES
    (user_bob_id, 'Early morning chest session done! Consistency is key. How did you start your day? #chestday #gymlife #discipline', 'https://images.unsplash.com/photo-1577221084712-45b044c676d4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80', ARRAY['text']::post_type_enum[], 'public', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day');

END $$;